#!/usr/bin/env php
<?php

// How to use: cat data/message_1.json | ./convert_to_latex > data/content.tex 
// All files: rm data/content.tex && ls data/message_*.json | xargs -I'{}' sh -c 'cat {} | ./convert_to_latex >> data/content.tex'


$data = json_decode(stream_get_contents(fopen('php://stdin', 'r')), true);

$currentYear = 0;
$currentMonth = 0;
$currentDay = 0;

$data['messages'] = array_reverse($data['messages']);

$counter = 0;
foreach ($data['messages'] as $msg) {
	if (!isset($msg['content'])) {
		continue;
	}

	$sender = utf8_decode($msg['sender_name']);
	$content = str_replace(['\\', '{', '}', '%', '^', '#', '$', '_', '&'], ['\\\\', '\{', '\}', '\%', '\^{}', '\#', '\$', '\_{}', '\&'], utf8_decode($msg['content']));
	$date = new DateTimeImmutable("@" . ($msg['timestamp_ms']/1000));

	$year = $date->format('Y');
	if ($currentYear !== $year) {
		echo '\newyear{', $year, '}', PHP_EOL;
		$currentYear = $year;
		$currentMonth = 0;
		$currentDay = 0;
	}
	$month = $date->format('m');
	if ($currentMonth !== $month) {
		echo '\newmonth{', $month, '}', PHP_EOL;
		$currentMonth = $month;
		$currentDay = 0;
	}
	$day = $date->format('d');
	if ($currentDay !== $day) {
		echo '\newday{', $day, '}', PHP_EOL;
		$currentDay = $day;
	}
       
	$content = preg_replace('/([^-\p{L}\x00-\x7F]+)/u', '{\\fontspec{Symbola.ttf}\1}', $content);
	echo "\\fbmessage{", PHP_EOL;
	echo "\datetime{", $date->format('d.m.Y H:i'), "}", PHP_EOL;
	echo "\sender{", $sender, "}", PHP_EOL;
	echo "\content{", $content, "}", PHP_EOL;
	echo "}", PHP_EOL;
	echo PHP_EOL;

	if (++$counter > 1000) {
#		die;
	}
}
