services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    _instanceof:
        Symfony\Component\Console\Command\Command:
            tags: ['command']
        Wildledersessel\Fbmbook\Preprocessing\ChatPart\Media\MediaTypeProcessorInterface:
            tags: ['preprocess.mediatype']
        Wildledersessel\Fbmbook\Preprocessing\ChatPart\ChatPartProcessorInterface:
            tags: ['preprocess.chattype']

    Wildledersessel\Fbmbook\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Wildledersessel\Fbmbook\Application:
        public: true
        arguments:
            - !tagged command

    Wildledersessel\Fbmbook\Preprocessing\ChatPart\Media\DelegatingMediaProcessor:
        public: true
        arguments:
            - !tagged preprocess.mediatype

    Wildledersessel\Fbmbook\Preprocessing\ChatPart\Processor:
        public: true
        arguments:
            - !tagged preprocess.chattype
